# .github/workflows/update-flake.yml
name: Update Flake Inputs

on:
  schedule:
    # Run every Tuesday at 7:00 AM UTC (after Dependabot runs)
    - cron: '0 7 * * 2'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    name: Update Nix Flake Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v18

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Update flake inputs
        run: |
          # Get current commit for comparison
          CURRENT_LOCK_HASH=$(sha256sum flake.lock | cut -d' ' -f1)
          
          # Update all flake inputs
          nix flake update
          
          # Check if anything changed
          NEW_LOCK_HASH=$(sha256sum flake.lock | cut -d' ' -f1)
          
          if [ "$CURRENT_LOCK_HASH" = "$NEW_LOCK_HASH" ]; then
            echo "No updates available"
            echo "HAS_UPDATES=false" >> $GITHUB_ENV
          else
            echo "Updates found"
            echo "HAS_UPDATES=true" >> $GITHUB_ENV
          fi

      - name: Verify updated configuration
        if: env.HAS_UPDATES == 'true'
        run: |
          echo "Verifying flake after updates..."
          nix flake check --all-systems --no-build

      - name: Generate update summary
        if: env.HAS_UPDATES == 'true'
        run: |
          echo "## Flake Input Updates" > update_summary.md
          echo "" >> update_summary.md
          echo "This PR updates all Nix flake inputs to their latest versions." >> update_summary.md
          echo "" >> update_summary.md
          echo "### Changed Inputs" >> update_summary.md
          echo "" >> update_summary.md
          
          # Show what changed in flake.lock
          if git diff --name-only | grep -q "flake.lock"; then
            echo "\`\`\`diff" >> update_summary.md
            git diff flake.lock >> update_summary.md
            echo "\`\`\`" >> update_summary.md
          fi
          
          echo "" >> update_summary.md
          echo "### Verification" >> update_summary.md
          echo "" >> update_summary.md
          echo "- ✅ Flake check passed" >> update_summary.md
          echo "- ✅ All system configurations validated" >> update_summary.md
          echo "" >> update_summary.md
          echo "**Auto-generated by GitHub Actions**" >> update_summary.md

      - name: Create Pull Request
        if: env.HAS_UPDATES == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "deps(nix): update flake inputs"
          title: "chore: update Nix flake inputs"
          body-path: update_summary.md
          branch: automated/update-flake-inputs
          delete-branch: true
          labels: |
            dependencies
            nix-flake
            automated
          reviewers: jacobmolnia  # Replace with your GitHub username
          assignees: jacobmolnia  # Replace with your GitHub username

      - name: Enable auto-merge
        if: env.HAS_UPDATES == 'true'
        run: |
          # Wait for PR to be created
          sleep 10
          
          # Find the PR number
          PR_NUMBER=$(gh pr list --head automated/update-flake-inputs --json number --jq '.[0].number')
          
          if [ ! -z "$PR_NUMBER" ]; then
            echo "Enabling auto-merge for PR #$PR_NUMBER"
            gh pr merge $PR_NUMBER --auto --squash
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}